TypeError bug in python3
TypeError: a bytes-like object is required, not 'str'

Receive this error when attempting to generate the bootstrap.json file on python 3.8.1 and 3.7.6. However, the current code still works on 2.7.x. Tested the proposed fix on 3.8.1, 3.7.6, and 2.7.16, so it should be backward compatible with older versions of 3.8.